[package]
name = "nidrs-openapi"
version = "0.1.0"
authors = ["WumaCoder <wumacoder@gmail.com>"]
description = "Nidrs openapi library."
keywords = ["nidrs", "axum", "http", "web", "framework"]
categories = ["network-programming", "asynchronous", "web-programming::http-server", "web-programming::websocket"]
publish = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
serde_json = "1.0.115"
serde = "1.0.197"
thiserror = "1.0.58"
axum = "0.7.5"
utoipa = "4.2.3"
utoipa-swagger-ui = { version = "7", features = ["axum"] }
utoipa-redoc = { version = "4.0.0", features = ["axum"] }
utoipa-scalar = { version = "0.1.0", features = ["axum"] }
utoipa-rapidoc = { version = "4.0.0", features = ["axum"] }

nidrs-openapi-macro = { workspace = true }
nidrs-extern = { workspace = true }
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
